"""新增订单表, 盲盒表, 普通商品表

Revision ID: 1276f8ce964f
Revises: 
Create Date: 2024-07-28 17:46:17.623934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1276f8ce964f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mystery-box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normal-box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normal_mystery',
    sa.Column('normal_box_id', sa.Integer(), nullable=True),
    sa.Column('mystery_box_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mystery_box_id'], ['mystery-box.id'], ),
    sa.ForeignKeyConstraint(['normal_box_id'], ['normal-box.id'], )
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'USERCANCELLED', 'SYSTEMCANCELLED', 'FAILED', name='orderstatus'), nullable=True),
    sa.Column('normal_box_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['normal_box_id'], ['normal-box.id'], name='normal_box_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('normal_mystery')
    op.drop_table('normal-box')
    op.drop_table('mystery-box')
    # ### end Alembic commands ###
