"""普通商品,盲盒商品添加库存字段.

Revision ID: 89b30336ec54
Revises: 1276f8ce964f
Create Date: 2024-07-28 20:08:52.554567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b30336ec54'
down_revision = '1276f8ce964f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mystery-box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stock', sa.Integer(), nullable=True, comment='当前库存'))
        batch_op.add_column(sa.Column('total_stock', sa.Integer(), nullable=True, comment='总库存'))

    with op.batch_alter_table('normal-box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stock', sa.Integer(), nullable=True, comment='当前库存'))
        batch_op.add_column(sa.Column('total_stock', sa.Integer(), nullable=True, comment='总库存'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normal-box', schema=None) as batch_op:
        batch_op.drop_column('total_stock')
        batch_op.drop_column('current_stock')

    with op.batch_alter_table('mystery-box', schema=None) as batch_op:
        batch_op.drop_column('total_stock')
        batch_op.drop_column('current_stock')

    # ### end Alembic commands ###
