"""订单表增加盲盒字段.

Revision ID: bd53be0c72e4
Revises: 89b30336ec54
Create Date: 2024-07-31 15:52:49.250653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd53be0c72e4'
down_revision = '89b30336ec54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mystery_box_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mystery-box', ['mystery_box_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mystery_box_id')

    # ### end Alembic commands ###
